route:
  group_by: ['alertname', 'team']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 6h
  receiver: email-logs
  routes:
  - match:
      team: leafs
    receiver: email-logs

inhibit_rules:
- source_match:
    severity: 'urgent'
  target_match:
    severity: 'warn'
  equal: ['alertname', 'instance']

receivers:
- name: email-logs
  email_configs:
